#!/bin/sh

# This adds a remote origin for newly initialized repos (not clones),
# useful for creating new dotfile repositories you plan to push.
#
# Avoid running during `vcsh clone`, which calls init() internally and
# would otherwise overwrite the remote that clone is about to set.
[ "$VCSH_COMMAND" = "init" ] || exit 0

# Do nothing if an origin is already configured.
vcsh "$VCSH_DIRECTORY" remote get-url origin >/dev/null 2>&1 && exit 0

base="${VCSH_REMOTE_BASE:-git@github.com:sabrehagen}"
vcsh "$VCSH_DIRECTORY" remote add origin "$base/$VCSH_DIRECTORY"
