#!/bin/sh

# This code does amost exactly what the native vcsh sanity checking code
# does except that on finding a potential merge conflict, it moves existing
# files out of the way temporarily. Merging (part of `vcsh clone`) happens
# cleanly, and a post-merge hook can be used to figure out what to do with
# the now-renamed files.

worktree="${VCSH_BASE:-$HOME}"
_branch="$(git symbolic-ref -q --short refs/remotes/origin/HEAD 2>/dev/null || echo master)"

git ls-tree -r --name-only "origin/$_branch" | while IFS= read -r object; do
  [ -e "$worktree/$object" ] && mv -- "$worktree/$object" "$worktree/$object.vcsh-unclobber"
done
