#!/bin/sh

# This code does amost exactly what the native vcsh sanity checking code
# does except that on finding a potential merge conflict, it moves existing
# files out of the way temporarily. Merging (part of `vcsh clone`) happens
# cleanly, and a post-merge hook can be used to figure out what to do with
# the now-renamed files.

worktree="${VCSH_BASE:-$HOME}"

git ls-tree -r --name-only origin/master | while IFS= read -r object; do
  if [ -e "$worktree/$object" ]; then
    printf '%s [pre-merge] repo=%s move=%s\n' \
      "$(date -Is 2>/dev/null || date)" \
      "${VCSH_REPO_NAME:-unknown}" \
      "$worktree/$object"
    mv -- "$worktree/$object" "$worktree/$object.vcsh-unclobber"
  fi
done
